language: node_js

services:
  - docker

before_install:
  - cd web_app
  - touch pg-init-scripts/data-base.env
  - touch .env

install:
  - docker-compose build

script:
  - docker-compose up -d
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload

after_success:
  - docker --version
  - docker-compose exec web npm run semantic-release
