language: node_js

services:
  - docker

before_install:
  - cd web_app
  - touch pg-init-scripts/data-base.env
  - touch .env

install:
  - docker-compose build

script:
  - echo "no hay tests"

after_install:
  - echo "nada por ahora"
