version: 0.0
os: linux

files:
  - source: scripts
    destination: iic2173-proyecto-semestral-grupo20/web_app

permissions:
  - object: scripts
    pattern: "**"
    owner: ubuntu

hooks:
  ApplicationStop:
    - location: stop.sh
      timeout: 600
      runas: ubuntu
  AfterInstall:
    - location: install.sh
      timeout: 600
      runas: ubuntu
  ApplicationStart:
    - location: start.sh
      timeout: 600
      runas: ubuntu
