version: 0.0
os: linux

files:
  - source: scripts
    destination: /opt/codedeploy-agent/deployment-root/531f9816-3538-436e-93d6-da801e7c5195/d-4ZCP5NG36/deployment-archive

permissions:
  - object: scripts
    pattern: "**"
    owner: ec2-user

hooks:
  ApplicationStop:
    - location: /opt/codedeploy-agent/deployment-root/531f9816-3538-436e-93d6-da801e7c5195/d-4ZCP5NG36/deployment-archive/stop.sh
      timeout: 600
      runas: ec2-user
  AfterInstall:
    - location: install.sh
      timeout: 600
      runas: ec2-user
  ApplicationStart:
    - location: start.sh
      timeout: 600
      runas: ec2-user
