version: "3"
services:
  db:
    container_name: "postgres_db"
    image: "postgres:12-alpine"
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    env_file:
      - ./pg-init-scripts/database.env
    ports:
      - "5432:5432"
    networks:
      - node-pg-connect
  
  redis:
    image: "redis"
    container_name: "cache"
    ports:
      - "6379:6379"
    networks:
      - node-pg-connect

  web:
    build: .
    container_name: "express_app"
    depends_on:
      - db
      - redis
    env_file:
      - ./.env
    networks:
      - node-pg-connect
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules

  webserver:
    image: nginx:mainline-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - web
    networks:
      - node-pg-connect

volumes:
  pg-init-scripts:
  nginx-conf:

networks:
  node-pg-connect:
    driver: bridge
