version: "3"

services:
   web:
      build: .
      container_name: "express_app"
      image: 161618437221.dkr.ecr.us-east-2.amazonaws.com/ass_g20
      env_file:
         - ./.env
      networks:
         - node-pg-connect
      ports:
         - "3000:3000"
      volumes:
         - .:/app
         - /app/node_modules
      restart: always


   webserver:
      image: nginx:mainline-alpine
      container_name: nginx
      restart: unless-stopped
      ports:
         - "80:80"
      volumes:
         - ./nginx-conf:/etc/nginx/conf.d
         #  - web-root:/var/www/html
         #  - certbot-etc:/etc/letsencrypt
         #  - certbot-var:/var/lib/letsencrypt
      depends_on:
         - web
      networks:
         - node-pg-connect

volumes:
   pg-init-scripts:
   nginx-conf:

networks:
   node-pg-connect:
     driver: bridge
